### ISSUE TITLE
why latin1 and not utf8 ?

### ISSUE THREAD

**Issue by benoitc** [tonyrog/tree_db#3]
I noticed in the `tree_db` module you're using `binary_to_atom(Bin, latin1)` , why `latin1` and not `utf8` ? Any reason for it?

**Comment by tonyrog** [comment]
I think the tree_db.erl module should be able to handle utf8 with out any problem now, the problem was that all elements must be less than ?top. Now then ?top is defined as <<>> and this term is greater than any atom. In the the tree_db_bin.erl (using binaries instead of atom, will probably replace tree_db at some point) the ?top is defined as <<255,255,255,255>> and as long as any utf8 is less than ?top this should be ok. If I remember correctly my thinking was also a very selfish one to only allow characters that I could read, stupid I now :-) Of course sorting of the siblings will depend on the internal sort order of utf8 atoms.
